- type: accessLevel
  id: Bar
  name: id-card-access-level-bar

- type: accessLevel
  id: Kitchen
  name: id-card-access-level-kitchen

- type: accessLevel
  id: Hydroponics
  name: id-card-access-level-hydroponics

- type: accessLevel
  id: Service
  name: id-card-access-level-service

- type: accessLevel
  id: Janitor
  name: id-card-access-level-janitor

- type: accessLevel
  id: Theatre
  name: id-card-access-level-theatre

- type: accessLevel
  id: Chapel
  name: id-card-access-level-chapel

- type: accessLevel
  id: Lawyer
  name: id-card-access-level-lawyer

- type: accessLevel
  id: Boxer
  name: id-card-access-level-boxer

- type: accessLevel
  id: Clown
  name: id-card-access-level-clown

- type: accessLevel
  id: Library
  name: id-card-access-level-library

- type: accessLevel
  id: Mime
  name: id-card-access-level-mime

- type: accessLevel
  id: Musician
  name: id-card-access-level-musician

- type: accessLevel
  id: Reporter
  name: id-card-access-level-reporter

- type: accessLevel
  id: Zookeeper
  name: id-card-access-level-zookeeper


- type: accessGroup
  id: Service
  tags:
  - HeadOfPersonnel
  - Bar
  - Kitchen
  - Hydroponics
  - Service
  - Janitor
  - Theatre
  - Chapel
  - Lawyer
  - Boxer # DeltaV - Add Boxer access
  - Clown # DeltaV - Add Clown access
  - Library # DeltaV - Add Library access
  - Mime # DeltaV - Add Mime access
  - Musician # DeltaV - Add Musician access
  - Reporter # DeltaV - Add Reporter access
  - Zookeeper # DeltaV - Add Zookeeper access
